name: Build Laravel ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, pdo_mysql, tokenizer, fileinfo, ctype, dom, json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare Laravel writable directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          chmod -R 777 bootstrap/cache storage

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install PHP deps (no dev)
        run: composer install --no-interaction --no-progress --prefer-dist --no-dev --optimize-autoloader

      - name: Install and build frontend
        run: |
          npm ci || npm install
          npm run build

      - name: Prepare release zips
        run: |
          mkdir -p release
          zip -rq release/project.zip . \
            -x ".git/*" ".github/*" "node_modules/*" "tests/*" ".env" \
               "storage/framework/cache/*" "storage/framework/sessions/*" "storage/framework/views/*"
          (cd public && zip -rq ../release/public.zip .)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-build
          path: release/*.zip
          retention-days: 7
